### ISSUE TITLE
can't find wechit/ folder to put the chrome driver

### ISSUE THREAD

**Issue by J-A-S-0-N** [LingDong-/wechit#5]
you said to locate the chrome driver into the wechit folder but i can't find wechit/ folder to put the chrome driver

**Comment by J-A-S-0-N** [comment]
should i just put driver = webdriver.Chrome(executable_path=r"C:\Program Files\chromedriver.exe")?

**Comment by J-A-S-0-N** [comment]
> should i just put driver = webdriver.Chrome(executable_path=r"C:\Program Files\chromedriver.exe")?

but where do i put it?

**Comment by J-A-S-0-N** [comment]
and if i open https://web.wechat.com this and scan the QR code this pop up <error><ret>1203</ret><message>To protect your account, logging in to WeChat via the web has been suspended. Use WeChat for Windows or WeChat for Mac to log in on a computer. Download WeChat for Windows or Mac at http://wechat.com.</message></error> will this effect anything?

**Comment by LingDong-** [comment]
Hi @J-A-S-0-N , the `wechit` folder is simply the folder that contains this repo after you download/clone it (because this repo is called `wechit`).

If logging into WeChat via the web has been suspended for you, then I'm afraid I cannot help about it because the chrome driver logs you in by manipulating the web interface. Maybe it'll be un-suspended if you wait long enough? I haven't encountered this issue before, sorry.

Thank you.

**Comment by J-A-S-0-N** [comment]
oh thanks for the information awesome code btw great job
